apiVersion: v1
kind: Service
metadata:
 labels:
   name: {{ .Release.Name }}-{{ .Chart.Name }}
 name: {{ .Release.Name }}-{{ .Chart.Name }}
 namespace: test-api-dev
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  type: {{ .Values.service.type }}

