apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: test-api-dev
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: kaushikrahul08/webapp:latest
        ports:
        - containerPort: 8000
